### ISSUE TITLE
WAP to merge 2 linklist

### ISSUE THREAD

**Issue by sonal3yadav** [sonal3yadav/DSA#16]

**Comment by aadi-raj** [comment]
Hi, can you assign this issue to me?

**Comment by Visbhavesh** [comment]
hey @sonal3yadav assign me this issue

**Comment by sonal3yadav** [comment]
assigned @aadi-raj @Visbhavesh

**Comment by deepti-29** [comment]
Hello,
Can you please assign me this issue?
